# Generated by Django 5.0.1 on 2024-01-25 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=200)),
                ('post_type', models.CharField(choices=[('javascript', 'Javascript Vanila'), ('typescript', 'Typescript Vanila'), ('python', 'Python Vanila'), ('next_js', 'Next Js'), ('react', 'React'), ('react_movile', 'React Mobile'), ('django', 'Django'), ('flask', 'Flask'), ('ninja', 'Ninja'), (None, None), ('test', 'Pruebas de testeo')], default=None, max_length=50)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('filetype', models.CharField(default='text/markdown', max_length=255)),
                ('content', models.TextField(default='###NONE')),
                ('article', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.articles')),
            ],
        ),
    ]
