# Generated by Django 5.0.1 on 2024-01-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_postsrepository_delete_postrepository'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsrepository',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='postsrepository',
            name='post_type',
            field=models.CharField(choices=[('javascript', 'Javascript vanila'), ('typescript', 'Typescript vanila'), ('python', 'Python vanila'), ('next_js', 'Next Js'), ('react', 'react'), ('react_movile', 'React Mobile'), ('django', 'Django'), ('flask', 'Flask'), ('ninja', 'ninja'), (None, None), ('test', 'Pruebas de testeo')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='postsrepository',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
